language: node_js
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/.bin/gulp tsd
  - ./node_modules/.bin/gulp browserify-test
